-- MySQL Script generated by MySQL Workbench
-- Thu Mar 27 11:55:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pooldb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pooldb` ;

-- -----------------------------------------------------
-- Schema pooldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pooldb` DEFAULT CHARACTER SET utf8 ;
USE `pooldb` ;

-- -----------------------------------------------------
-- Table `pooldb`.`datestamp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pooldb`.`datestamp` ;

CREATE TABLE IF NOT EXISTS `pooldb`.`datestamp` (
  `datestamp_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  PRIMARY KEY (`datestamp_id`),
  UNIQUE INDEX `time_of_measure_id_UNIQUE` (`datestamp_id` ASC) VISIBLE,
  UNIQUE INDEX `date_UNIQUE` (`date` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooldb`.`pool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pooldb`.`pool` ;

CREATE TABLE IF NOT EXISTS `pooldb`.`pool` (
  `pool_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gallons` INT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`pool_id`),
  UNIQUE INDEX `pool_id_UNIQUE` (`pool_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooldb`.`measurements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pooldb`.`measurements` ;

CREATE TABLE IF NOT EXISTS `pooldb`.`measurements` (
  `pool_id` INT UNSIGNED NOT NULL,
  `datestamp_id` INT UNSIGNED NOT NULL,
  `time` TIME NOT NULL,
  `free_chlorine` FLOAT UNSIGNED NULL,
  `combined_chlorine` FLOAT NULL,
  `ph` FLOAT NULL,
  `total_alkalinity` FLOAT NULL,
  `calcium_hardness` FLOAT NULL,
  `status` TINYINT NOT NULL,
  `status_message` ENUM('all chemicals at regular levels', 'high free chlorine', 'low free chlorine', 'high combined chlorine', 'low combined chlorine', 'high alkalinity', 'low alkalinity', 'other') NOT NULL,
  `other_message` VARCHAR(45) NULL,
  PRIMARY KEY (`pool_id`, `datestamp_id`),
  INDEX `fk_pool_timestamp_timestamp1_idx` (`datestamp_id` ASC) VISIBLE,
  INDEX `fk_pool_timestamp_pool_idx` (`pool_id` ASC) VISIBLE,
  CONSTRAINT `fk_pool_timestamp_pool`
    FOREIGN KEY (`pool_id`)
    REFERENCES `pooldb`.`pool` (`pool_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pool_timestamp_timestamp1`
    FOREIGN KEY (`datestamp_id`)
    REFERENCES `pooldb`.`datestamp` (`datestamp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
