-- MySQL Script generated by MySQL Workbench
-- Thu Mar 27 12:27:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pooldb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pooldb` ;

-- -----------------------------------------------------
-- Schema pooldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pooldb` DEFAULT CHARACTER SET utf8 ;
USE `pooldb` ;

-- -----------------------------------------------------
-- Table `pooldb`.`datestamp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pooldb`.`datestamp` ;

CREATE TABLE IF NOT EXISTS `pooldb`.`datestamp` (
  `datestamp_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  PRIMARY KEY (`datestamp_id`),
  UNIQUE INDEX `time_of_measure_id_UNIQUE` (`datestamp_id` ASC) VISIBLE,
  UNIQUE INDEX `date_UNIQUE` (`date` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooldb`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pooldb`.`city` ;

CREATE TABLE IF NOT EXISTS `pooldb`.`city` (
  `city_id` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooldb`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pooldb`.`state` ;

CREATE TABLE IF NOT EXISTS `pooldb`.`state` (
  `state_id` INT NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`state_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooldb`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pooldb`.`country` ;

CREATE TABLE IF NOT EXISTS `pooldb`.`country` (
  `country_id` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooldb`.`pool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pooldb`.`pool` ;

CREATE TABLE IF NOT EXISTS `pooldb`.`pool` (
  `pool_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gallons` INT NULL,
  `city_id` INT NOT NULL,
  `state_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`pool_id`),
  UNIQUE INDEX `pool_id_UNIQUE` (`pool_id` ASC) VISIBLE,
  INDEX `fk_pool_city1_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_pool_state1_idx` (`state_id` ASC) VISIBLE,
  INDEX `fk_pool_country1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_pool_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `pooldb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pool_state1`
    FOREIGN KEY (`state_id`)
    REFERENCES `pooldb`.`state` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pool_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `pooldb`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooldb`.`measurements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pooldb`.`measurements` ;

CREATE TABLE IF NOT EXISTS `pooldb`.`measurements` (
  `pool_id` INT UNSIGNED NOT NULL,
  `datestamp_id` INT UNSIGNED NOT NULL,
  `time` TIME NOT NULL,
  `free_chlorine` FLOAT UNSIGNED NULL,
  `combined_chlorine` FLOAT NULL,
  `ph` FLOAT NULL,
  `total_alkalinity` FLOAT NULL,
  `calcium_hardness` FLOAT NULL,
  PRIMARY KEY (`pool_id`, `datestamp_id`),
  INDEX `fk_pool_timestamp_timestamp1_idx` (`datestamp_id` ASC) VISIBLE,
  INDEX `fk_pool_timestamp_pool_idx` (`pool_id` ASC) VISIBLE,
  CONSTRAINT `fk_pool_timestamp_pool`
    FOREIGN KEY (`pool_id`)
    REFERENCES `pooldb`.`pool` (`pool_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pool_timestamp_timestamp1`
    FOREIGN KEY (`datestamp_id`)
    REFERENCES `pooldb`.`datestamp` (`datestamp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooldb`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pooldb`.`status` ;

CREATE TABLE IF NOT EXISTS `pooldb`.`status` (
  `status_id` INT NOT NULL,
  `status_message` ENUM('all chemicals at regular levels', 'high free chlorine', 'low free chlorine', 'high combined chlorine', 'low combined chlorine', 'high alkalinity', 'low alkalinity', 'other') NOT NULL,
  `other_message` VARCHAR(45) NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooldb`.`measurements_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pooldb`.`measurements_status` ;

CREATE TABLE IF NOT EXISTS `pooldb`.`measurements_status` (
  `pool_id` INT UNSIGNED NOT NULL,
  `datestamp_id` INT UNSIGNED NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`pool_id`, `datestamp_id`, `status_id`),
  INDEX `fk_measurements_status_status1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_measurements_status_measurements1_idx` (`pool_id` ASC, `datestamp_id` ASC) VISIBLE,
  CONSTRAINT `fk_measurements_status_measurements1`
    FOREIGN KEY (`pool_id` , `datestamp_id`)
    REFERENCES `pooldb`.`measurements` (`pool_id` , `datestamp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_measurements_status_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `pooldb`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
